### PR TITLE
Use Text PropTypes instead of object

### PR DESCRIPTION
**Pull request by benadamstyles**
Fixes https://github.com/adorableio/react-native-animated-ellipsis/issues/4

### CODE REVIEW

**Comment by BaseCase** [comment]
Hi @Leeds-eBooks, thanks for the PR! Merging now :)

**Comment by benadamstyles** [comment]
No problem, thanks for this lib!

**Comment by itsthatguy** [comment]
@BaseCase @Leeds-eBooks would this fit better as the following? Or is that what `Text.propTypes.style` does?

```
style: PropTypes.oneOfType([
  Text.propTypes.style,
  PropTypes.object
])
```

**Comment by BaseCase** [comment]
@itsthatguy it looks like `Text.propTypes.style` handles that. Or at least, in my limited testing, I was able to pass both plain objects and StyleSheet references using it.

**Comment by itsthatguy** [comment]
:+1:

**Pull request merged**
